# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Thompson 
email: netengr2009@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Hi my name is Andrew.  I'm a driven engineer with experience in 
  config management, cloud, Ruby, Elasticsearch, and much more.  
  I tout myself as a strong leader with exceptional analytical and
  problem solving skills with the ability to work under pressure.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devkmsg.github.io" # the base hostname & protocol for your site
twitter_username: devkmsg
personal_github_username: devkmsg
work_github_username: athompson-r7
linkedin_profile: https://www.linkedin.com/in/andrew-thompson-90487a7
resume_url: "https://devkmsg.github.io/resume/AndrewThompsonResume.pdf"

# Build settings
markdown: kramdown
